### PR TITLE
merge request: provided_magic

### PR DESCRIPTION
**Pull request by vanHoesel**
add `provided_deref` and `provided_maybe`

initially, I was only going to support dereferencing a HASH-ref or an ARRAY-ref with `provided_ref`. That was the use case for the company.

But than I started thinking about other references (hey, deref could apply to anything), so CODE-refs and SCALAR-refs ar done too.

And what about objects, but then what about private keys ... so, `provided_maybe` is fully DWIM and also stops seeping in `$key => undef` pairs

### CODE REVIEW

**Comment by vanHoesel** [comment]
This relates to issue #3

**Comment by vanHoesel** [comment]
Oh ... interestingly enough, this also covers:

https://github.com/holcapek/p5-perlx-maybe/tree/master-lazy-provided

**Comment by tobyink** [comment]
I like `provided_deref` but `provided_maybe` seems badly named. I realize you're not a native English speaker, so you're at a slight disadvantage. I'm using the word "provided" to mean "if"… like *provided the weather is good, we'll have a picnic*. So `provided_maybe` doesn't really give any hints for what the function is doing.

Anyway, here's an idea…

1. We keep `provided_deref` as it is (though because we're getting rid of `provided_maybe`, we can remove the `_provided_maybe` hidden function and just combine it into one function.

2. Add a feature that if the second argument to `provided_deref` is blessed into `PerlX::Maybe` (or maybe create a dummy package for this), it will have the magic pairwise filtering turned on.

3. Create a function to bless stuff into `PerlX::Maybe`. Unless someone can think of a better name, let's call that `filter_with_maybe`.

Then instead of:
```
provided_maybe $employee, $employee,
```

You'd write:
```
provided_deref $employee, filter_with_maybe $employee,
```

**Comment by vanHoesel** [comment]
Sure, English is probably my 3rd language i learned (after german), not sure which language i use most though.

`provided_maybe` of course, would be the combination between `provided_deref` and `maybe` (minus private attributes). That sounded pretty obvious to me.

I'm not so fond of the `filter_with_maybe`nifty solution. It starts me to make me wonder what the difference is between a `maybe` and `filter with maybe`. Also, what could one do with the `filter with maybe` functionallity on its own ? I know... since you explained it, it's just a wrapper to bless the next argument into some structure, such that `provided_deref` knows how to treat it.

And secondly, it feels a bit odd to have this extra keyword in the middle

I'd much more would see it as a different function/subroutine ... with a different name:
- provided_deref_with_maybe
- provided_deref_clean
- provided_deref_dwim

**Comment by tobyink** [comment]
`provided_deref_with_maybe` isn't bad.

**Comment by vanHoesel** [comment]
`provided_deref_with_maybe` it will be, although it is a silly name. Because what is 'include' ar the ones that are surely needed, not maybe :-)

I'll rename it and commit to my branch. So all you would have to do, is merge it and make it release ready etc.

**Comment by tobyink** [comment]
Okay, so merged and I made a few optimizations and other tweaks.

One thing though — it seems to me that `provided_deref_with_maybe` should do the `maybe` filtering not just on hashrefs and blessed objects, but also on arrayrefs and the list returned by coderefs. Unless you have any particular justification for *not* filtering those, I'll probably change the current behaviour in these cases.

**Comment by vanHoesel** [comment]
You are great!

that was typical a `GOTO` that is totally fine 👍

I did had my thoughts about the `maybe` in the `provided_deref_with_maybe`, however, I do not feel comfortable to make a judgement on that one... should a ARRAYref then be treated pairwise ? With a HASHref, I can understand the intent, to skip key/value pairs when the value is undefined. I do not know what the dereferenced LIST of unknown 'values' might be

**Comment by tobyink** [comment]
Yes, an arrayref should be treated pairwise. Dealing with lists of key-value pairs is pretty much the entire point of this module.

And if you didn't want that behaviour, you could just use `provided_deref` anyway.

**Comment by vanHoesel** [comment]
That last sentence is indeed the correct way to approach it ... if one does not want that behaviour, use the `provided_deref` , it makes totally sense now.

ARRAYref treating pairwise, makes sense, i can fix that.

SCALARref can not be handled pairwise, obviously ... so skip undef, pass otherwise ?

What to do with the last element of an odd list, it has no paired element ... thus it's undef, and thus do never pass .... but we don't do that for a scalar, which does not have a paired element...

And the result of a CODEref, I tend to re-evaluate that through the thing again, since we do not know what it returns... it could be a single scalar, which contains a reference to a whatever OR it could be an entire list, possibly a key/value pair, possibly a (odd) list

But I'm quite willing to pickup and write a patch for the ARRAYref and SCALAR, once decided what to do with odd number off elements and an undefined value for the SCALARref.

**Comment by tobyink** [comment]
Already done, and released as 1.200.

**Pull request merged**
